In [1]:
import torch

import torch.nn.functional as F



In [2]:
torch.__version__

'2.5.1+cu124'

In [3]:
#scaler
sclaer = torch.tensor(6)
sclaer.ndim

0

In [4]:
sclaer.item()

6

In [5]:
sclaer

tensor(6)

In [6]:
# create vector

vector =  torch.tensor([7,7])

vector , vector.ndim

(tensor([7, 7]), 1)

In [7]:
vector.shape

torch.Size([2])

In [8]:
matrics = torch.tensor([[4,3], [4,5]])

matrics, matrics.ndim ,matrics.shape

(tensor([[4, 3],
         [4, 5]]),
 2,
 torch.Size([2, 2]))

In [9]:
#creating a random tensor

random_tensor = torch.rand(size=(3,4)) # size=(3,4) , by defualt float32
random_tensor ,random_tensor.dtype

(tensor([[0.0192, 0.4267, 0.9605, 0.3362],
         [0.3406, 0.0419, 0.8233, 0.2728],
         [0.4926, 0.3658, 0.5701, 0.1347]]),
 torch.float32)

In [10]:
device = "CUDA" if torch.cuda.is_available() else "CPU"
device

'CUDA'

In [11]:
x_tensor = torch.rand(size=(224,224,3))
x_tensor , x_tensor.shape , x_tensor.ndim

(tensor([[[0.1301, 0.6594, 0.1212],
          [0.4639, 0.8167, 0.6094],
          [0.5781, 0.0917, 0.5505],
          ...,
          [0.2767, 0.3083, 0.0611],
          [0.3722, 0.5297, 0.2191],
          [0.7714, 0.1954, 0.7544]],
 
         [[0.6890, 0.8057, 0.0515],
          [0.5904, 0.8633, 0.1954],
          [0.9843, 0.5136, 0.4258],
          ...,
          [0.3350, 0.5173, 0.4947],
          [0.1037, 0.7995, 0.8966],
          [0.8542, 0.9295, 0.9277]],
 
         [[0.0798, 0.3878, 0.0116],
          [0.5915, 0.9475, 0.6941],
          [0.9026, 0.9946, 0.9762],
          ...,
          [0.4820, 0.9722, 0.4943],
          [0.8332, 0.2727, 0.3950],
          [0.7681, 0.6085, 0.0339]],
 
         ...,
 
         [[0.5499, 0.2533, 0.5085],
          [0.7612, 0.6409, 0.5757],
          [0.8376, 0.9404, 0.4080],
          ...,
          [0.1545, 0.0460, 0.9858],
          [0.4087, 0.2298, 0.2864],
          [0.4364, 0.5461, 0.7193]],
 
         [[0.6248, 0.5918, 0.8115],
          [0

In [12]:
x_tensor.dtype

torch.float32

In [13]:
#arange
x_tensor = torch.arange(start=0,end= 5, step=2)

In [14]:
x_tensor , x_tensor.shape , x_tensor.ndim

(tensor([0, 2, 4]), torch.Size([3]), 1)

In [15]:
ones_tensor = torch.ones(size=(3,4))
ones_tensor , ones_tensor.dtype , ones_tensor.shape , ones_tensor.ndim

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32,
 torch.Size([3, 4]),
 2)

In [16]:
zero_tensor = torch.zeros(size=(3,4))
zero_tensor , zero_tensor.dtype , zero_tensor.shape , zero_tensor.ndim

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32,
 torch.Size([3, 4]),
 2)

In [17]:
zero_tensor.device

device(type='cpu')

In [18]:
r_tensor = torch.tensor([2,3,4],
                        dtype=torch.float64,
                        device= "cpu")

In [19]:
r_tensor

tensor([2., 3., 4.], dtype=torch.float64)

In [20]:
     # tensor operations
# multiply
# addition
# subtraction
# division

In [21]:
x=torch.tensor([1,2,3])
y=torch.tensor([4,5,6])

z = x + y

In [22]:
z , z.shape , z.ndim , z.dtype

(tensor([5, 7, 9]), torch.Size([3]), 1, torch.int64)

In [23]:
z * 3

tensor([15, 21, 27])

In [24]:
# multipule

f = torch.multiply(x,10)

In [25]:
f

tensor([10, 20, 30])

In [26]:
s = torch.matmul(x,y)

In [27]:
s

tensor(32)

In [28]:
s.shape , x.ndim

(torch.Size([]), 1)

In [29]:
rndome_state = torch.manual_seed(42)
seed = torch.rand(3,4)
seed

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

In [30]:
from torch import nn

In [31]:
Linear_layer = nn.Linear(in_features=7, out_features=6)


In [32]:
#state_dict()
Linear_layer , Linear_layer.weight , Linear_layer.bias , Linear_layer.out_features , Linear_layer.in_features , Linear_layer.state_dict()

(Linear(in_features=7, out_features=6, bias=True),
 Parameter containing:
 tensor([[ 0.2792,  0.0512,  0.1822, -0.0534,  0.2914,  0.0559, -0.1764],
         [ 0.0963, -0.1741, -0.0443, -0.1535,  0.2507, -0.2984, -0.1742],
         [-0.1067, -0.2273,  0.0357, -0.3733,  0.3413, -0.3211,  0.2918],
         [ 0.0629, -0.1227,  0.2336,  0.0589,  0.3054,  0.0413, -0.1192],
         [ 0.1016, -0.1025,  0.1591,  0.3375,  0.2185, -0.1652,  0.2182],
         [ 0.0676,  0.1919, -0.2304, -0.3742, -0.1460, -0.2899,  0.3101]],
        requires_grad=True),
 Parameter containing:
 tensor([ 0.1089,  0.1566,  0.1195, -0.0066,  0.2958, -0.2685],
        requires_grad=True),
 6,
 7,
 OrderedDict([('weight',
               tensor([[ 0.2792,  0.0512,  0.1822, -0.0534,  0.2914,  0.0559, -0.1764],
                       [ 0.0963, -0.1741, -0.0443, -0.1535,  0.2507, -0.2984, -0.1742],
                       [-0.1067, -0.2273,  0.0357, -0.3733,  0.3413, -0.3211,  0.2918],
                       [ 0.0629, -0.122

In [33]:
tensor_L = torch.rand(4,7)

In [34]:
k = Linear_layer(tensor_L)

In [35]:
k , k.shape

(tensor([[ 0.4182, -0.0129,  0.2905,  0.2863,  0.8251, -0.4020],
         [ 0.3958, -0.1545, -0.3574,  0.3182,  0.6510, -0.9726],
         [ 0.3142, -0.1221, -0.1536,  0.2763,  0.5980, -0.8375],
         [ 0.3392, -0.2563, -0.4503,  0.1621,  0.5298, -0.7291]],
        grad_fn=<AddmmBackward0>),
 torch.Size([4, 6]))

In [36]:
v = torch.arange(0,16,2)
v

tensor([ 0,  2,  4,  6,  8, 10, 12, 14])

In [37]:
v.min()

tensor(0)

In [38]:
v.max()

tensor(14)

In [39]:
v.argmax()

tensor(7)

In [40]:
v.argmin()

tensor(0)

In [41]:
v.shape

torch.Size([8])

In [42]:
# transpose , reashape()
v_Reshape = v.reshape(-1,1)
v_tensor_transpose = torch.transpose(v_Reshape,dim0=1,dim1=0)


In [43]:
v_Reshape.shape

torch.Size([8, 1])

In [44]:
v_tensor_transpose.shape

torch.Size([1, 8])

In [45]:
v_tensor_transpose_t = v_tensor_transpose.t()

In [46]:
v_tensor_transpose_t.shape

torch.Size([8, 1])

In [47]:
v.dtype

torch.int64

In [48]:
v=v.type(torch.float32)

In [49]:
v.dtype

torch.float32

In [50]:
#mean
mean_v =v.mean()

In [51]:
mean_v

tensor(7.)

In [52]:
b = torch.rand(size=(3,4))

In [53]:
b.shape

torch.Size([3, 4])

In [54]:
b=b.reshape(4,3)
b.shape

torch.Size([4, 3])

In [55]:
# satck

x_stack = torch.stack([x,x,x,x])

In [56]:
x_stack

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])

In [57]:
v_tensor_transpose_t.shape

torch.Size([8, 1])

In [58]:
# how delete the dim1 whaich equal 1

v_tensor_transpose__squaze = torch.squeeze(v_tensor_transpose_t)

In [59]:
v_tensor_transpose__squaze.shape

torch.Size([8])

# please looke the diff

In [60]:
v_tensor_transpose__unsquaze = torch.unsqueeze(v_tensor_transpose__squaze,dim=1)

In [61]:
v_tensor_transpose__unsquaze.shape

torch.Size([8, 1])

# refactor_or reconstruct

In [62]:
i = torch.rand(224,228,3)
i.shape

torch.Size([224, 228, 3])

In [63]:
i_permute = torch.permute(i,dims=(2,0,1))  # (3,224,228)
i_permute.shape

torch.Size([3, 224, 228])

# convert from numpy to tensor

In [64]:
import numpy as np

In [65]:
g = np.random.rand(3,4)

In [66]:
type(g)

numpy.ndarray

In [67]:
g.dtype

dtype('float64')

In [68]:
converter = torch.from_numpy(g)

In [69]:
type(converter)

torch.Tensor

In [70]:
!nvidia-smi

Sat Feb  1 01:53:50 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   37C    P8             12W /   70W |       2MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [71]:
torch.cuda.device_count()

1

## to_device GPU(cuda) ,CPU

In [72]:
tensor_d = torch.rand(4,5)

In [73]:
tensor_d.device

device(type='cpu')

In [74]:
if torch.cuda.is_available():
    tensor_d_cuda = tensor_d.to("cuda")

In [75]:
tensor_d=tensor_d.to("cuda")

In [76]:
tensor_d.device

device(type='cuda', index=0)

In [77]:
tensor_d=tensor_d.to("cpu")

In [78]:
tensor_d.device

device(type='cpu')

In [79]:
type(tensor_d)

torch.Tensor

In [80]:
tensor_d=tensor_d.numpy()

In [81]:
type(tensor_d)

numpy.ndarray